import type { Metadata } from "next";
import { ModeProvider, ModeToggle } from "@/registry/components/mode-toggle";
import { baloo2, notoSansJP } from "@/styles/fonts";

import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body className={`${notoSansJP.variable} ${baloo2.variable} antialiased`}>
        <ModeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="flex h-16 shrink-0 items-center justify-between gap-2">
            <h1>nobcn</h1>
            <ModeToggle />
          </header>
          <main className="flex flex-1 flex-col gap-4 p-4 pt-0">
            {children}
          </main>
        </ModeProvider>
      </body>
    </html>
  );
}
